### ISSUE TITLE
NFC with PKPassLibrary (suppressed Apple Pay)

### ISSUE THREAD

**Issue by SurpriseMF3000** [codereviewcache/DisableApplePay#1]
Hello,
can you still use NFC when Apple Pay is blocked with the PKPassLibrary - requestAutomaticPassPresentationSuppression method?

Thanks for answers!

**Comment by joma-s** [comment]
Yes,
That’s the whole point of the suppression, so you can use the NFC and the device won’t show the apple wallet while close to the device. Be aware that one of Apple’s requirements is that the suppression doesn’t take longer then 10 seconds (I think it applies to most cases).
